services:
  # Nginx reverse proxy
  oneserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oneserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cert:/etc/nginx/ssl:ro
      - ./nginx-logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - oneserver_bridge

networks:
  oneserver_bridge:
      name: oneserver_bridge
      external: true
      attachable: true