services:
  # Nginx reverse proxy
  oneserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oneserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./settings.json:/app/settings.json:ro
      - ./cert:/etc/nginx/ssl:ro
      - ./nginx-logs:/var/log/nginx
    restart: unless-stopped